---
- name: create terraform home dir
  file:
    state: directory
    path: "{{ terraform_config_home }}"

- include_tasks: setup_config.yml
  loop: "{{ configs|dict2items }}"
  loop_control:
    loop_var: item
